### ISSUE TITLE
The list of stack stop scrolling on increase number of card.

### ISSUE THREAD

**Issue by gkundu17** [mutualmobile/CardStackUI#22] opened 2016-09-08 13:38 UTC
Hi,
Implement the given library with mine project and its work fine.
But as per my project requirement the number of card increase dynamically according to the user contact
data ,not able to perform the 3rd and 4th mentioned animation (Basic Drag and Parallax Drag)

**Comment by tushar-acharya** [comment] 2016-10-06 03:27
Duplicate of #25

**Closed by tushar-acharya** 2016-10-06 03:27 UTC
